// List of ISO 3166-1 alpha-2 country codes
const countryCodesAndFacts = {
  "AE": "The UAE is known for its futuristic skyscrapers, including the Burj Khalifa, and its oil wealth.",
  "AF": "The country is home to the world’s highest paved road, the Pamir Highway, which reaches an elevation of 4,655 meters (15,272 feet).",
  "AG": "Antigua has 365 beaches, one for each day of the year.",
  "AI": "Anguilla is a British overseas territory in the Caribbean, known for its stunning white-sand beaches and crystal-clear waters. It has no rivers and only a few natural lakes.",
  "AL": "Albania is one of the few countries in Europe to have a total lack of snakes.",
  "AM": "Armenia was the first country in the world to adopt Christianity as its state religion in 301 AD.",
  "AO": "The Angolan civil war, which lasted from 1975 to 2002, was one of the longest-running conflicts in African history.",
  "AR": "Argentina is home to the world’s southernmost city, Ushuaia, located on the Tierra del Fuego archipelago.",
  "AS": "American Samoan cuisine relies on locally grown ingredients.",
  "AT": "Austria is known for its rich cultural heritage, especially in classical music, being the home of composers like Mozart and Beethoven.",
  "AU": "Australia is the world’s smallest continent but the sixth-largest country by land area.",
  "AW": "The Island of Aruba Was Once Known As 'The Island of Giants.",
  "AX": "Åland is the sunniest place in the Nordic countries in May–August.",
  "AZ": "Azerbaijan is known as the 'Land of Fire' due to the abundance of natural gas and oil fields that cause flames to emerge from the earth.",
  "BA": "Bosnia and Herzegovina has the world’s only forest made entirely of pine trees, called the 'Blidinje Nature Park.",
  "BB": "Barbados is known for its white sandy beaches and is also the birthplace of rum.",
  "BD": "Bangladesh is the world’s largest producer of jute, a plant used for making burlap sacks, ropes, and twine.",
  "BE": "Belgium is famous for its chocolate, beer, and waffles, and it has over 200 types of beer.",
  "BF": "Burkina Faso has no access to the ocean, making it one of the few landlocked countries in West Africa.",
  "BG": "Bulgaria has a rich history of rose cultivation and is the world’s leading producer of rose oil.",
  "BH": "Bahrain is an archipelago made up of 33 islands, and the country has a rich history of pearl diving.",
  "BI": "Burundi is one of the smallest countries in Africa, yet it has one of the highest population densities in the world.",
  "BJ": "Benin is the birthplace of the voodoo religion, and it is still practiced in parts of the country today.",
  "BL": "The Saint Barthélemy island is both mountainous, with a maximum elevation of 921 feet (281 metres), and fertile, despite relatively little rainfall.",
  "BM": "Bermuda is known as the 'Shipwreck Capital of the Atlantic' with over 300 documented shipwrecks.",
  "BN": "Brunei has a very small population but is one of the richest countries in the world due to its oil and gas reserves.",
  "BO": "Bolivia’s Salar de Uyuni is the world’s largest salt flat and is so vast that it is used as a mirror for the sky during the rainy season.",
  "BQ": "Bonaire's airport is called Flamingo Airport. That's because the island is home to over 10,000 of the pink birds.",
  "BR": "Brazil is home to the Amazon Rainforest, which is the largest tropical rainforest in the world.",
  "BS": "The Bahamas is home to the world’s third-largest barrier reef.",
  "BT": "Bhutan is the only country in the world to measure its success by “Gross National Happiness” rather than GDP.",
  "BV": "The Bouvet Island is the only known breeding ground of the royal penguin, one of some 25 bird species that breed there.",
  "BW": "Botswana is home to one of the largest salt pans in the world, the Makgadikgadi Pan.",
  "BY": "Belarus has 11,000 lakes, including Lake Naroch, the largest lake in the country.",
  "BZ": "Belize is home to the Great Blue Hole, a giant marine sinkhole that is a popular diving destination.",
  "CA": "Canada has the longest coastline of any country in the world, stretching over 202,000 kilometers.",
  "CC": "Cocos Islands' territory consists of two atolls made up of 27 coral islands, of which only two – West Island and Home Island – are inhabited. ",
  "CD": "The DRC has vast mineral resources, including diamonds, cobalt, and copper.",
  "CF": "The Central African Republic is home to one of the largest remaining tracts of tropical rainforests in the world.",
  "CG": "The country is home to the Congo River, which is the second-longest river in Africa.",
  "CH": "Switzerland is a multilingual country, with four official languages: German, French, Italian, and Romansh.",
  "CI": "Côte d'Ivoire boasts the largest church in the world with an area of 30,000 square meters.",
  "CK": "More Cook Islanders live overseas than on the main island.",
  "CL": "Chile is home to the Atacama Desert, which is one of the driest places on Earth.",
  "CM": "Cameroon is often referred to as “Africa in miniature” because of its diverse geography, ranging from beaches to mountains and rainforests.",
  "CN": "China has the world’s largest population, with over 1.4 billion people.",
  "CO": "Colombia is known for its coffee, and it is one of the largest coffee producers in the world.",
  "CR": "Costa Rica is known for its biodiversity, with over 5% of the world’s species living within its borders.",
  "CU": "Cuba is the largest island in the Caribbean and has a rich cultural heritage shaped by African, Spanish, and Native American influences.",
  "CV": "Cabo Verde has no rivers, making it one of the driest countries in the world.",
  "CW": "Curacao’s official language is called Papiamento, which is a unique blend of Spanish, Portuguese and Dutch with a hint of English and French thrown in.",
  "CX": "Nicknamed the 'Galapagos of the Indian Ocean', the island is famous for its red crabs, sea birds, whale sharks and spectacular coral reefs.",
  "CY": "Cyprus is the birthplace of the ancient Greek goddess Aphrodite.",
  "CZ": "The country is home to the world’s oldest operating brewery, established in 993 AD.",
  "DE": "Germany is known for its engineering and is the birthplace of famous car brands like Mercedes-Benz, BMW, and Audi.",
  "DJ": "Djibouti has one of the hottest climates in the world, with some areas experiencing temperatures above 50°C (122°F).",
  "DK": "Denmark is the world’s happiest country according to the World Happiness Report.",
  "DM": "Dominica is known for its natural hot springs and rainforests, including the Boiling Lake, the second-largest volcanic lake in the world.",
  "DO": "The Dominican Republic is home to the Caribbean’s only rainforest, the Los Haitises National Park.",
  "DZ": "Algeria is the largest country in Africa by land area.",
  "EC": "Ecuador is named after the equator, which runs through the country.",
  "EE": "Estonia is one of the most digitally advanced countries, with e-residency and online voting systems.",
  "EG": "Egypt is home to the Great Pyramids of Giza, one of the Seven Wonders of the Ancient World.",
  "EH": "Western Sahara hosts the second largest wall in the world, coming up short only to the Great Wall of China.",
  "ER": "Eritrea has nine recognized ethnic groups, with Tigrinya being the most widely spoken language.",
  "ES": "Spain is famous for its rich cultural heritage, including Flamenco music and dance, as well as its architectural wonders like the Sagrada Familia.",
  "ET": "Ethiopia is one of the oldest countries in the world, with a history dating back over 3,000 years.",
  "FI": "Finland is known for its 188,000 lakes and is often considered one of the happiest countries in the world.",
  "FJ": "Fiji is made up of more than 300 islands, many of which are uninhabited.",
  "FM": "Micronesia – or the Federated States of Micronesia – is a collection of more than 600 islands in the heart of the Pacific Ocean.",
  "FO": "The population of the Faroe Islands consists of 80 different nationalities.",
  "FR": "France is home to the world-famous Eiffel Tower, a symbol of Paris and one of the most visited monuments in the world.",
  "GA": "Gabon has one of the highest forest cover percentages in the world, with over 80% of its land area covered by rainforests.",
  "GB": "The United Kingdom comprises England, Scotland, Wales, and Northern Ireland.",
  "GD": "Grenada is known as the 'Spice Isle' because it is one of the world’s largest producers of nutmeg and mace.",
  "GE": "Georgia is home to the ancient wine-producing region of Kakheti, where wine has been made for over 8,000 years.",
  "GF": "The capital city name of French Guiana comes from the Cayenne Pepper.",
  "GG": "Guernsey has one of the world's largest tidal ranges.",
  "GH": "Ghana was the first African country to gain independence from colonial rule, in 1957.",
  "GI": "The Great Siege (1779-1783) took place in Gibraltar at the same time as the American War of Independence.",
  "GL": "Greenland is the world’s largest island that is not a continent.",
  "GM": "Gambia is the smallest country on the African mainland, with a length of only 400 kilometers (250 miles).",
  "GN": "Guinea is rich in natural resources, especially bauxite, which is used to produce aluminum.",
  "GP": "Slavery was abolished in Guadeloupe until May 28th, 1848. It had been a major issue in the country for many years.",
  "GQ": "Equatorial Guinea is the only African nation with Spanish as an official language. It gained independence from Spain on October 12, 1968.",
  "GR": "Greece is home to the ancient city of Athens, which is considered the cradle of Western civilization.",
  "GT": "Guatemala is home to the ancient Mayan city of Tikal, a UNESCO World Heritage site.",
  "GU": "Guam has one of the tallest mountains on Earth, Mount Lamlam, but most of the mountain is underwater so it only rises 1,332 feet above sea level.",
  "GW": "Once hailed as a potential model for African development, the country is now one of the poorest in the world.",
  "GY": "Guyana is the only country in South America where English is the official language.",
  "HK": "Hong Kong used to be a fishing village.",
  "HM": "Volcanic in origin, Heard Island is 27 miles (43 km) long, 13 miles (21 km) wide, and rises to 9,005 feet (2,745 metres) at Mawson Peak on Big Ben Mountain.",
  "HN": "Honduras is home to the largest Mayan archaeological site in Central America, Copán.",
  "HR": "Croatia has over 1,000 islands, many of which are uninhabited.",
  "HT": "Food insecurity: Nearly half of the Haitian population (5.4 million people) are affected by acute hunger, with 2 million facing emergency levels of hunger.",
  "HU": "Hungary is famous for its thermal baths, many of which date back to the Turkish occupation in the 16th century.",
  "ID": "Indonesia is made up of over 17,000 islands, making it the largest archipelago in the world.",
  "IE": "Ireland is known for its lush green landscapes, earning it the nickname 'The Emerald Isle.'",
  "IL": "Israel is the only country where Hebrew is an official language and is home to the ancient city of Jerusalem.",
  "IN": "India is home to the world’s largest film industry, Bollywood, producing more films annually than any other country.",
  "IO": "The territory, an archipelago of 58 islands sometimes referred to as the Chagos Archipelago, covers some 640,000 sq km of ocean.",
  "IQ": "Iraq is home to some of the world’s earliest civilizations, including the Sumerians, Babylonians, and Assyrians.",
  "IR": "Iran is one of the oldest continuous major civilizations, with a history dating back more than 5,000 years.",
  "IS": "Iceland is home to over 130 volcanoes, and it’s one of the most geologically active countries on Earth.",
  "IT": "Italy is famous for its historical landmarks, such as the Colosseum and the Leaning Tower of Pisa.",
  "JE": "Jersey is the biggest of the Channel Islands.",
  "JM": "Jamaica is the birthplace of reggae music and the famous singer Bob Marley.",
  "JO": "Jordan is home to Petra, one of the Seven Wonders of the Ancient World.",
  "JP": "Japan is known for its technological advancements and is home to the world’s first bullet train.",
  "KE": "Kenya is famous for its wildlife and is home to some of the world’s best-known national parks and safaris.",
  "KG": "Kyrgyzstan is home to the Tian Shan mountain range, which offers some of the best hiking and climbing in Central Asia.",
  "KH": "Cambodia is home to Angkor Wat, the largest religious monument in the world.",
  "KI": "Kiribati is one of the most remote countries in the world, made up of 33 islands in the central Pacific Ocean.",
  "KM": "Comoros is an island nation located between Madagascar and the coast of Mozambique.",
  "KN": "It’s said that St. Kitts and Nevis are so fertile that even the monkeys are green, and you’ll see colonies of them scampering freely beside the roads and beaches.",
  "KP": "North Korea is one of the most secretive countries in the world, with limited access for foreign visitors.",
  "KR": "South Korea is known for its rapid technological development, including Samsung and LG electronics.",
  "KW": "Kuwait has one of the world’s highest per capita incomes, largely due to its oil wealth.",
  "KY": "Grand Cayman is prone to sea pirate invasions. These usually happen during Pirate’s Week which runs from November 12th through the 22nd.",
  "KZ": "Kazakhstan is the world’s largest landlocked country.",
  "LA": "Laos is the only landlocked country in Southeast Asia.",
  "LB": "Lebanon has been famous for its cedar trees, which were used by ancient civilizations to build ships.",
  "LC": "The Sulphur Springs in Soufriere are often described as the only drive-in volcano in the Caribbean, and possibly the world.",
  "LI": "Liechtenstein is one of the richest countries in the world by GDP per capita, despite being a small landlocked nation.",
  "LK": "Sri Lanka is known as the 'Pearl of the Indian Ocean' due to its natural beauty.",
  "LR": "Liberia is the only African country to have been founded by freed American slaves in the 19th century.",
  "LS": "Lesotho is a landlocked country entirely surrounded by South Africa, and it has the highest average altitude of any country.",
  "LT": "Lithuania is known for being the first country to declare independence from the Soviet Union in 1990.",
  "LU": "Luxembourg is one of the wealthiest countries in the world, with a very high standard of living.",
  "LV": "Latvia is known for its beautiful medieval architecture and is home to one of the longest beaches in Europe.",
  "LY": "Libya has the largest oil reserves in Africa and has been a major player in the global energy market.",
  "MA": "Morocco is home to the world’s largest desert, the Sahara, which spans across much of North Africa.",
  "MC": "Monaco is the second smallest country in the world and is famous for its luxurious lifestyle and the Monte Carlo casino.",
  "MD": "Moldova has one of the largest wine cellars in the world, located in Cricova.",
  "ME": "Montenegro is known for its stunning Adriatic coastline and the Bay of Kotor, a UNESCO World Heritage site.",
  "MF": "St. Maarten / St. Martin is known as the culinary capital of the Caribbean.",
  "MG": "Madagascar is famous for its unique wildlife, including lemurs that are found nowhere else on Earth.",
  "MH": "There are 29 separate atolls in the Marshalls, containing a total of 1,225 islands, 870 reef systems, and 160 species of coral.",
  "MK": "The official language of Macedonia is Macedonian, which is a South Slavic language closely related to Bulgarian and Serbian.",
  "ML": "Mali has 13 official languages, of which Bambara is the most commonly spoken.",
  "MM": "Myanmar is the largest country by area in Mainland Southeast Asia and has a population of about 55 million.",
  "MN": "Mongolia has the lowest population density in the world, with vast stretches of land and few people.",
  "MO": "The gambling industry of Macau is seven times larger than that of Las Vegas.",
  "MP": "During the colonial period, the Northern Marianas were variously under the control of the Spanish, German, and Japanese empires.",
  "MQ": "Martinique is the rum capital of the world and is home to 12 different brands of rum.",
  "MR": "The country's name derives from Mauretania, the Latin name for a region in the ancient Maghreb.",
  "MS": "Montserrat is home to the critically endangered giant ditch frog, known locally as the 'mountain chicken.",
  "MT": "Malta has a rich history and was the site of many historical sieges, including the Great Siege of 1565.",
  "MU": "Mauritius is known for its biodiverse flora and fauna with many unique species endemic to the country.",
  "MV": "The Maldives is an island nation known for its crystal-clear waters, coral reefs, and luxury resorts.",
  "MW": "The Southern African country is famous for its smiling, friendly people, and its slow and easy approach to life, as well as its extraordinary freshwater lake and its exceptional natural scenery.",
  "MX": "Mexico is the birthplace of chocolate, and it was the first country to cultivate cacao.",
  "MY": "Malaysia is known for its diverse culture and the Petronas Twin Towers, the tallest buildings in the world from 1998 to 2004.",
  "MZ": "Mozambique is known for its stunning coastline, which is home to beautiful beaches and marine biodiversity.",
  "NA": "Namibia is famous for its unique landscape, including the world’s highest sand dunes in the Namib Desert.",
  "NC": "New Caledonia boasts the world's largest lagoon of 24,000 km²",
  "NE": "Niger is home to the largest concentration of prehistoric rock art in the world, in the Air Mountains.",
  "NF": "Norfolk Island is famous around the world for being a bird watcher's paradise.",
  "NG": "Nigeria is the most populous country in Africa and is home to more than 200 million people.",
  "NI": "Nicaragua is known for its volcanoes and is home to the world’s largest volcanic island, Ometepe.",
  "NL": "The Netherlands is known for its windmills, tulip fields, and an extensive canal system in Amsterdam.",
  "NO": "Norway is famous for its fjords, which are steep, glacial valleys found along the coast.",
  "NP": "Nepal is the only country in the world that does not have a rectangular flag.",
  "NR": "Phosphate has been mined on Nauru since 1907.",
  "NU": "Niue Used to Have a Pokemon Currency",
  "NZ": "New Zealand is home to unique wildlife, including the kiwi bird, which is a national symbol.",
  "OM": "The Omani people boast of a virtually non-existent crime rate.",
  "PA": "Panama is home to the Panama Canal, which connects the Atlantic and Pacific Oceans.",
  "PE": "Peru is home to the ancient Inca city of Machu Picchu, one of the New Seven Wonders of the World.",
  "PF": "The national flower of Tahiti is the tiare. It is customary to put one behind your left ear if you’re taken, or your right ear if you’re looking for love.",
  "PG": "Papua New Guinea is home to over 800 languages, the highest number of languages spoken in any country.",
  "PH": "The Philippines host the largest underground river in the world",
  "PK": "Pakistan has the world’s largest irrigation system, which supports its vast agricultural industry.",
  "PL": "Poland is home to the world’s largest castle, the Malbork Castle, built by the Teutonic Knights.",
  "PM": "Saint Pierre and Miquelon have their own time zone, this one being 30 minutes ahead of Newfoundland time.",
  "PN": "Pitcairn is accessible only by boat through Bounty Bay, due to the island's steep cliffs.",
  "PR": "The piña colada was invented in Puerto Rico.",
  "PT": "Portugal is famous for its port wine, which is produced in the Douro Valley.",
  "PW": "Palau is the only country where Japanese is the official language de jure (by law).",
  "PY": "Paraguay is one of the few countries in the world to have no official capital. Asunción is considered the de facto capital.",
  "QA": "Qatar has the world’s highest per capita income, largely due to its natural gas and oil reserves.",
  "RE": "La Réunion was uninhabited until French immigrants and colonial subjects settled the island in the 17th century.",
  "RO": "Romania is home to the legendary Dracula, whose story is based on Vlad the Impaler, a 15th-century prince.",
  "RS": "Serbia is home to the medieval monasteries of the Fruška Gora, which are a UNESCO World Heritage site.",
  "RU": "Russia is the largest country in the world by land area, spanning 11 time zones.",
  "RW": "One of the smallest countries in Africa, mountainous Rwanda is referred to as the 'land of a thousand hills.'",
  "SA": "Saudi Arabia is home to Mecca and Medina, two of the holiest cities in Islam.",
  "SB": "The Solomon Islands' coastline totals an impressive 5,313 kilometres in length.",
  "SC": "Seychelles was once a pirate hideout, in particular Anse Forbans (Pirate’s Cove) on Mahé and Côte d’Or on Praslin.",
  "SD": "Sudan is home to some of the oldest civilizations in Africa and has a rich history of pyramids and ancient kingdoms.",
  "SE": "Sweden is famous for its beautiful landscapes, being the birthplace of IKEA, and for its innovation in technology and design.",
  "SG": "Singapore is a global financial hub and is known for its cleanliness, modern architecture, and impressive skyline.",
  "SH": "St Helena is home to the oldest land animal on Earth - Jonathan the Tortoise.",
  "SI": "Slovenia is famous for its picturesque Lake Bled, its extensive cave systems, and its rich green forests.",
  "SJ": "The island (Svalbard and Jan Mayen) was first discovered by Dutch whaler Jan Jacobszoon May van Schellinkhout in 1614, after whom it is named.",
  "SK": "Slovakia is known for its medieval castles, high mountain ranges, and the UNESCO-listed town of Banská Štiavnica.",
  "SL": "On 4 August 1964, Sierra Leone introduced its own currency, the Sierra Leonean Leone, to replace the British West African pound.",
  "SM": "San Marino is one of the world’s oldest republics, founded in AD 301.",
  "SN": "The name 'Senegal' comes from the Wolof phrase ‘Sunuu Gaal’, which translates as ‘Our Boat’; they are a nation of fishermen and a gentle, welcoming people.",
  "SO": "In Somalia, camels are immensely important both economically and culturally.",
  "SR": "Suriname's economy is dependent on its extensive supply of natural resources, most notably bauxite, of which it is one of the top producers in the world.",
  "SS": "South Sudan's protected area of Bandingilo National Park hosts the second-largest wildlife migration in the world.",
  "ST": "At sea level, the Sao Tome and Principe islands have a tropical climate hot and humid and the yearly temperatures average at about 27⁰C.",
  "SV": "El Salvador is known as the 'Land of Volcanoes' due to the number of volcanoes making up its geography.",
  "SX": "St. Martin's Dutch side is known for its festive nightlife, beaches, jewellery, drinks made with native rum-based guavaberry liquors, and casinos.",
  "SY": "The Syrian conflict has raged longer than the two World Wars",
  "SZ": "Known as the Switzerland of Africa, Eswatini comprises magnificent mountain scenery with unique, ancient rock formations",
  "TC": "The first known inhabitants of the Turks and Caicos islands were Tainos (also called “Lucayans”). These original settlers appear to have arrived around the year 750 AD from other islands in the Caribbean.",
  "TD": "Chad - home to over 200 ethnic groups who speak over 100 languages, it's little wonder Chad earned the moniker 'Babel Tower of the World.",
  "TF": "The French Southern Territories are special for many reasons, but mostly their remote location has allowed the lands to remain untouched and wild.",
  "TG": "Togo’s artisans are skilled in creating beautiful woven textiles, wood carvings, pottery and metalwork, showcasing the artistic heritage of the nation.",
  "TH": "Thailand is famous for its beautiful beaches, ancient temples, and vibrant street food culture.",
  "TJ": "Tajikistan is known for its rugged mountains and ancient Silk Road cities.",
  "TK": "The Pacific island nation of Tokelau is one of the most remote places on the planet, and, with the entire country sitting metres above sea level, one of the most under threat from climate change.",
  "TL": "Timor-Leste is the first new country of the 21st century.",
  "TM": "Turkmenistan is home to the 'Door to Hell,' a natural gas field that has been burning for decades.",
  "TN": "Tunisia is home to ancient ruins, including Carthage, and its diverse landscapes, from Mediterranean beaches to desert landscapes.",
  "TO": "Tonga is an island nation known for its Polynesian culture and being the only Pacific island monarchy.",
  "TR": "Turkey is a country that straddles two continents, Asia and Europe, and is known for its rich history, including the ancient city of Troy.",
  "TT": "Trinidad and Tobago is noted within the Caribbean region for its ethnic, religious and cultural diversity and tolerance.",
  "TV": "On 15 November 2022, amidst sea level rises, Tuvalu announced plans as the first country in the world to build a self-digital replica in the metaverse in order to preserve its cultural heritage.",
  "TZ": "Tanzania is home to Mount Kilimanjaro, the highest peak in Africa, and the Serengeti National Park, famous for its wildlife migration.",
  "UA": "Ukraine is known for its vast steppes, beautiful cities like Kyiv, and the Chernobyl disaster site.",
  "UG": "Uganda is known for its rich wildlife, including the endangered mountain gorillas that live in its forests.",
  "US": "The US was involved in both World War I and World War II.",
  "UY": "Uruguay is known for its progressive policies, stunning beaches, and being one of the safest countries in Latin America.",
  "UZ": "Uzbekistan came under Russian control in the 19th Century, and emerged as an independent state when Soviet rule ended in 1991.",
  "VA": "The Pope is the ruler of both Vatican City State and the Holy See.",
  "VC": "St Vincent is a volcanic island with an active volcano called La Soufriere which means 'Sulphur Mine'.",
  "VE": "Venezuela is home to the world's tallest waterfall, the Angel Falls, and rich in natural resources and beauty.",
  "VG": "Unlike the rest of the United States, in the U.S. Virgin Islands, vehicles drive on the left side of the road.",
  "VI": "The U.S. Virgin Islands were originally inhabited by the Ciboney and Arawaks, with some scholars thinking that the islands were inhabited from as early as 1000 BC.",
  "VN": "Vietnam is a long, narrow nation shaped like the letter 's'.",
  "VU": "Vanuatu is located in the South Pacific Ocean in Oceania. Vanuatu is an archipelago of about 80 smaller islands, 65 of these are inhabited.",
  "WF": "Wallis and Futuna officially became a French Colony in 1924.",
  "WS": "Samoa gained independence from New Zealand in 1962. The country was referred to as Western Samoa until 1997.",
  "YE": "Yemen is a UNESCO World Heritage site and is known for its rich biodiversity.",
  "ZA": "South Africa has the world’s biggest land mammal, the African elephant, and the biggest reptile, the leatherback turtle.",
  "ZM": "One of Africa's oldest refugee settlements is located in Zambia.",
  "ZW": "The world’s largest man-made lake is in Zimbabwe"
};


// Country code to country name mapping
const countryNames = {
  "AE": "The United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Bonaire",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos Islands",
  "CD": "Democratic Republic of Congo",
  "CF": "Central African Republic",
  "CG": "Congo",
  "CH": "Switzerland",
  "CI": "Côte d'Ivoire",
  "CK": "Cook Island",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curacao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "The United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HM": "Heard Island",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KA": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts and Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxemburg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "St. Maarten / St. Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "Macedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macau",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "The Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "The Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "The Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "La Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "The Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "St Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard and Jan Mayen",
  "SK": "Sierra Leone",
  "SL": "Slovakia",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome and Principe",
  "SV": "El Salvador",
  "SX": "St. Martin(Dutch)",
  "SY": "Syria",
  "SZ": "Switzerland",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TF": "The French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad",
  "TV": "Tuvalu",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "US": "The United States of America",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "The Holy See",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela",
  "VG": "Virgin Islands (UK)",
  "VI": "Virgin Islands (US)",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

// Sorting the country codes alphabetically
const sortedCountryCodes = [...Object.keys(countryCodesAndFacts)].sort();

// Function to dynamically create flags
function createFlags() {
  const flagsContainer = document.getElementById('flags-container');

  sortedCountryCodes.forEach(code => {
    const flagImg = document.createElement('img');
    flagImg.src = `https://flagcdn.com/h80/${code.toLowerCase()}.png`; // Flag CDN
    flagImg.alt = `${countryNames[code]} Flag`;
    flagImg.classList.add('flag');
    flagImg.dataset.country = code; // Store country code in data attribute
    flagsContainer.appendChild(flagImg);
  });
}

// Function to display a fact about the clicked country
function displayFact(countryCode) {
  const countryName = countryNames[countryCode] || countryCode; // Get full name, fallback to code
  const fact = countryCodesAndFacts[countryCode] || "No fact available for this country.";

  document.getElementById('country-name').textContent = countryName;
  document.getElementById('country-fact').textContent = fact;
}

// Event delegation for flag clicks
document.getElementById('flags-container').addEventListener('click', (event) => {
  if (event.target.classList.contains('flag')) {
    displayFact(event.target.dataset.country);
  }
});

// Create flags when the page loads
window.addEventListener('DOMContentLoaded', createFlags);
